Feature (#3)

diff --git a/.github/workflows/dev-plan.yaml b/.github/workflows/dev-plan.yaml
--- a/.github/workflows/dev-plan.yaml
+++ b/.github/workflows/dev-plan.yaml
@@ -1,16 +1,19 @@
 name: 'plan DEV'
 
+
 on:
   #pull_request:
-  push:
+   push:
     branches:
-      - main
+     - feature
     # path:
     #   - terraform/**
 
 env:
   AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
-  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_ID}}   
+  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_ID}}
+  #GITHUB_TOKEN: ${{secrets.GITH_TOKEN}}
+  #REGISTRY: ghcr.io
 
 
 jobs:
@@ -42,27 +45,110 @@ jobs:
         continue-on-error: true
         working-directory: ${{ env.WORKING_DIRECTORY }}    
 
+
+      - name: Run tfsec with reviewdog output on the PR
+        uses: reviewdog/action-tfsec@master
+        with:
+          github_token: ${{ secrets.GITH_TOKEN }}
+          working_directory: ./terraform # Change working directory
+          level: info # Get more output from reviewdog
+          reporter: github-pr-review # Change reviewdog reporter
+          #filter_mode: nofilter # Check all files, not just the diff
+          fail_on_error: true # Fail action if errors are found
+          flags: -tee # Add debug flag to reviewdog
+          #tfsec_flags: "" # Optional
+
+
       - name: 'Terraform init'
         id: init
         run: terraform init 
         working-directory: ${{ env.WORKING_DIRECTORY }}
+        # env:
+        #   TF_VAR_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
 
       - name: 'Terraform plan'
         id: plan
         run: terraform plan -no-color
         working-directory: ${{ env.WORKING_DIRECTORY }}
+        # env:
+        #   TF_VAR_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1 
+
+      - name: 'Terraform apply'
+        id: apply
+        run: terraform apply -auto-approve -input=false
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+     
+     
+        # env:
+        #   TF_VAR_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+
+
+      # - name: 'Terraform destroy'
+      #   id: destroy
+      #   run: terraform destroy -auto-approve -input=false
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}
+      #   env:
+      #     TF_VAR_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+
 
 # python lint
 
-  flake8-lint:
-    runs-on: ubuntu-latest
-    name: Lint
-    steps:
-      - name: Check out source repository
-        uses: actions/checkout@v2
-      - name: Set up Python environment
-        uses: actions/setup-python@v2
-        with:
-          python-version: "3.8"
+  # python-lint:
+  #   runs-on: ubuntu-latest
+  #   name: Lint
+  #   steps:
+  #   - name: Lint with pylint
+  #     run: |
+  #       pip install pylint
+  #       pylint .
+
+    #   - name: Check out source repository
+    #     uses: actions/checkout@v2
+    #   - name: Set up Python environment
+    #     uses: actions/setup-python@v2
+    #     with:
+    #       python-version: "2.7"
     #   - name: flake8 Lint
     #     uses: py-actions/flake8@v2   
+    
+ 
+  docker-build-and-push:
+    runs-on: ubuntu-latest
+    name: docker build and push
+    needs: make_stru_test
+    steps:
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+    #   - name: Login to DockerHub
+    #     uses: docker/login-action@v1 
+    #     with:
+    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
+    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
+      
+    #   - name: Build and push
+    #     uses: docker/build-push-action@v2
+    #     with:
+    #       push: true
+    #       tags: serwol/app:latest
+          
+          
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: serwol2 #${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      
+      - name: Build and push docker image
+        uses: docker/build-push-action@v2
+        with:
+         # context: .
+          push: true
+          tags: ghcr.io/serwol2/app:latest
